baseURL = "https://criptixo.xyz"
languageCode = "en-us"
title = "criptixo's webpage"
copyright = "criptixo"
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set

summaryLength = 5

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "dark"
  rss = true
  googleAnalyticsAsync = false
  showAllPostsArchive = false

  # Home page settings
  description = "I’m that kind of person that is very interested in random technology stuff."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false
  postsOnHomePage = 5 
  tagsOverview = 'false'
  showProjectsList = true
  projectsUrl = "https://github.com/criptixo"

  dateFormat = "2006-01-02"

  # Post page settings
  show_updated = true
  showReadTime = true

  [params.comments]
    enabled = false
    engine = "cactus_comments"
    [params.comments.utterances]
      repo = "<github_username>/<github_reponame>"
      label = "hugo-site-name"
      theme = "github-light"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" 
      #serverUrl = "" 
      #serverName = ""

  [[params.social]]
    name = "github"
    link = "https://github.com/criptixo"
  [[params.social]]
    name = "twitter"
    link = "https://www.twitter.com/criptixo"
   [[params.social]]
    name = "steam"
    link = "https://www.steamcommunity/id/criptixo" 
   [[params.social]]
    name = "lastfm"
    link = "https://www.last.fm/user/criptixo"
  [[params.social]]
    name = "email"
    link = "contact@criptixo.xyz"
