baseURL = "https://criptixo.xyz"
languageCode = "en-us"
title = "criptixo's webpage"
theme = "cactus"
copyright = "criptixo"
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set

summaryLength = 5

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "dark"
  rss = true
  googleAnalyticsAsync = false
  showAllPostsArchive = false

  # Home page settings
  description = "test"
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = flase
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/criptixo" # title link for projects list

  dateFormat = "2006-01-02"

  # Post page settings
  show_updated = true
  showReadTime = true

  [params.comments]
    enabled = true # default
    engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "<github_username>/<github_reponame>"
      label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
      theme = "github-light"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat

  [[params.social]]
    name = "github"
    link = "https://github.com/criptixo"
  [[params.social]]
    name = "twitter"
    link = "https://www.twitter.com/criptixo"
   [[params.social]]
    name = "steam"
    link = "https://www.steamcommunity/id/criptixo" 
   [[params.social]]
    name = "email"
    link = "conatact@criptixo.xyz"
  [[params.social]]
    name = "email"
    link = "conatact@criptixo.xyz"
